# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"P\n\rSignupRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"2\n\x0eSignupResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"B\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\"0\n\x10VerifyOTPRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0b\n\x03otp\x18\x02 \x01(\t\"L\n\x11VerifyOTPResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rsession_token\x18\x03 \x01(\t2\xb2\x01\n\x0b\x41uthService\x12\x33\n\x06Signup\x12\x13.auth.SignupRequest\x1a\x14.auth.SignupResponse\x12\x30\n\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x12<\n\tVerifyOTP\x12\x16.auth.VerifyOTPRequest\x1a\x17.auth.VerifyOTPResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNUPREQUEST']._serialized_start=20
  _globals['_SIGNUPREQUEST']._serialized_end=100
  _globals['_SIGNUPRESPONSE']._serialized_start=102
  _globals['_SIGNUPRESPONSE']._serialized_end=152
  _globals['_LOGINREQUEST']._serialized_start=154
  _globals['_LOGINREQUEST']._serialized_end=204
  _globals['_LOGINRESPONSE']._serialized_start=206
  _globals['_LOGINRESPONSE']._serialized_end=272
  _globals['_VERIFYOTPREQUEST']._serialized_start=274
  _globals['_VERIFYOTPREQUEST']._serialized_end=322
  _globals['_VERIFYOTPRESPONSE']._serialized_start=324
  _globals['_VERIFYOTPRESPONSE']._serialized_end=400
  _globals['_AUTHSERVICE']._serialized_start=403
  _globals['_AUTHSERVICE']._serialized_end=581
# @@protoc_insertion_point(module_scope)
